import { apiFetch, apiFetchBlob, apiFetchUpload } from "./apiClient";
import type {
  BulkUpdateCategoryResult,
  DeleteVariantResult,
  ImportProductsResult,
  Product,
  QuickCreateProductInput,
  QuickCreateProductResult,
  SetVariantStockResult,
  UpdateProductCategoryResult,
  UpdateProductCostResult,
  UpdateProductPriceResult,
  UpdateProductVariantInput,
  UpdateProductVariantResult,
  UploadProductImageResult,
} from "./types";

export function listProducts(brandId: string | null): Promise<Product[]> {
  const query = brandId ? `?brandId=${encodeURIComponent(brandId)}` : "";
  return apiFetch<Product[]>(`/api/products${query}`);
}

/** Backs the "+ Add Product" modal. */
export function createQuickProduct(input: QuickCreateProductInput): Promise<QuickCreateProductResult> {
  return apiFetch<QuickCreateProductResult>("/api/products/quick", {
    method: "POST",
    body: JSON.stringify(input),
  });
}

/** Backs the Edit modal's save action. */
export function updateProductVariant(
  variantId: string,
  input: UpdateProductVariantInput,
): Promise<UpdateProductVariantResult> {
  return apiFetch<UpdateProductVariantResult>(`/api/products/variants/${encodeURIComponent(variantId)}`, {
    method: "PATCH",
    body: JSON.stringify(input),
  });
}

/** Backs the row dropdown's Delete action. */
export function deleteProductVariant(variantId: string): Promise<DeleteVariantResult> {
  return apiFetch<DeleteVariantResult>(`/api/products/variants/${encodeURIComponent(variantId)}`, {
    method: "DELETE",
  });
}

/** Backs the Product Profile drawer's inline stock editor — `quantity` is the new total, not a delta. */
export function setVariantStock(variantId: string, quantity: number): Promise<SetVariantStockResult> {
  return apiFetch<SetVariantStockResult>(`/api/products/variants/${encodeURIComponent(variantId)}/stock`, {
    method: "PATCH",
    body: JSON.stringify({ quantity }),
  });
}

/** Backs the Product Profile drawer's "Update Product Price" field — sets one price across every variant of the product. */
export function updateProductPrice(productId: string, price: number): Promise<UpdateProductPriceResult> {
  return apiFetch<UpdateProductPriceResult>(`/api/products/${encodeURIComponent(productId)}/price`, {
    method: "PATCH",
    body: JSON.stringify({ price }),
  });
}

/** Backs the Product Profile drawer's "Update Production Cost" field — sets one cost across every variant of the product. */
export function updateProductCost(productId: string, cost: number): Promise<UpdateProductCostResult> {
  return apiFetch<UpdateProductCostResult>(`/api/products/${encodeURIComponent(productId)}/cost`, {
    method: "PATCH",
    body: JSON.stringify({ cost }),
  });
}

/** Backs the Product Profile drawer's Category selector — get-or-creates by name and applies it to the whole product. */
export function updateProductCategory(productId: string, category: string): Promise<UpdateProductCategoryResult> {
  return apiFetch<UpdateProductCategoryResult>(`/api/products/${encodeURIComponent(productId)}/category`, {
    method: "PATCH",
    body: JSON.stringify({ category }),
  });
}

/** Backs the products table's bulk-select "Set Category" action — one get-or-created category applied to every selected product. */
export function bulkUpdateProductsCategory(productIds: string[], category: string): Promise<BulkUpdateCategoryResult> {
  return apiFetch<BulkUpdateCategoryResult>("/api/products/bulk/category", {
    method: "PATCH",
    body: JSON.stringify({ productIds, category }),
  });
}

/** Backs the "Export Excel" button — a full .xlsx of every product/variant/SKU/price/stock. */
export function exportProductsWorkbook(brandId: string): Promise<Blob> {
  return apiFetchBlob(`/api/products/export?brandId=${encodeURIComponent(brandId)}`);
}

/** Backs the "Import Excel" button — uploads a .xlsx to create products or bulk-update price/stock. */
export function importProductsWorkbook(brandId: string, file: File): Promise<ImportProductsResult> {
  return apiFetchUpload<ImportProductsResult>(`/api/products/import?brandId=${encodeURIComponent(brandId)}`, file);
}

/** Backs the Add/Edit modal's file-upload image path — the file's raw bytes, not JSON. Sets the product's image directly server-side and returns the resulting URL. */
export function uploadProductImage(productId: string, file: File): Promise<UploadProductImageResult> {
  return apiFetchUpload<UploadProductImageResult>(`/api/products/${encodeURIComponent(productId)}/image`, file);
}

/**
 * Fetches the variant's QR sticker PNG (generated by the backend's
 * qrcode.util.ts, encoding the plain SKU) and returns a local object URL
 * suitable for an <img src>. Callers must URL.revokeObjectURL(...) it when
 * done to avoid leaking memory (see VariantPrintButton, BatchLabelPrintView).
 */
export async function fetchVariantQrCodeObjectUrl(sku: string): Promise<string> {
  const blob = await apiFetchBlob(`/api/products/variants/${encodeURIComponent(sku)}/qr-code`);
  return URL.createObjectURL(blob);
}
