import { apiFetch, apiFetchBlob } from "./apiClient";
import type { Product } from "./types";

export function listProducts(brandId: string | null): Promise<Product[]> {
  const query = brandId ? `?brandId=${encodeURIComponent(brandId)}` : "";
  return apiFetch<Product[]>(`/api/products${query}`);
}

/**
 * Fetches the variant's QR sticker PNG (generated by the backend's
 * qrcode.util.ts, encoding the plain SKU) and returns a local object URL
 * suitable for an <img src>. Callers must URL.revokeObjectURL(...) it when
 * done to avoid leaking memory (see QrCodeModal).
 */
export async function fetchVariantQrCodeObjectUrl(sku: string): Promise<string> {
  const blob = await apiFetchBlob(`/api/products/variants/${encodeURIComponent(sku)}/qr-code`);
  return URL.createObjectURL(blob);
}
